name: Build blog sources and publish
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: master
            - uses: sdkman/sdkman-action@master
              id: sdkman
              with:
                  candidate: java
                  version: 17.0.4.1-tem
            - uses: actions/setup-java@v1
              id: setup-java
              with:
                  java-version: 17.0.4.1
                  jdkFile: ${{ steps.sdkman.outputs.file }}
            - run: java --version
            - uses: wei/wget@v1
              with:
                  args: -q https://github.com/jbake-org/jbake/releases/download/v2.6.7/jbake-2.6.7-bin.zip -O jbake-2.6.7-bin.zip
            - uses: montudor/action-zip@v1
              with:
                  args: unzip -qq jbake-2.6.7-bin.zip -d .
            - run: sh jbake-2.6.7-bin/bin/jbake -b sources _site
            - uses: actions/upload-pages-artifact@v0
              with:
                  path: ./_site
                  retention-days: 1
            - uses: actions/deploy-pages@v1
              with:
                artifact_name: github-pages
                preview: false