name: Build blog sources and publish
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: renatoathaydes/setup-java-sdkman@v2.x
              with:
                candidate: jbake
                version: 2.6.7
            - run: jbake -b sources/ .