name: Build blog sources and publish
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: curl -s "https://get.sdkman.io" | bash
            - run: sdk install jbake
            - run: jbake -b