name: Build blog sources and publish
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: sdkman/sdkman-action@master
                id: sdkman
                with:
                    candidate: java
                    version: 17.0.4.1-tem